# -*- coding: utf-8 -*-
"""
Streamlit demo: Predict upstream water level for 3 hydropower dams.
- Single-file application (app.py). All assets under ./assets.
- Feature generation is aligned with the provided training notebooks:
  * Time features: hour, dow, month, is_weekend
  * Rolling stats: shift(1) then rolling(window, closed='left') for mean/std/max/min
  * Lags: row-based shift(l), with hourly data => 24 = 1 day

Author: generated by ChatGPT
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple, Optional

import joblib
import numpy as np
import pandas as pd
import streamlit as st


# =========================
# 1) CONFIG
# =========================
BASE_DIR = Path(__file__).parent
ASSETS_DIR = BASE_DIR / "assets"

@dataclass(frozen=True)
class DamConfig:
    dam_id: str
    dam_name: str
    data_csv: Path
    model_pkl: Path
    feats_json: Path
    target_col: str = "muc_nuoc_thuong_luu_m"
    time_col: str = "thoi_diem"


DAMS: Dict[str, DamConfig] = {
    "hoabinh": DamConfig(
        dam_id="hoabinh",
        dam_name="Hòa Bình",
        data_csv=ASSETS_DIR / "HoaBinh_merged.csv",
        model_pkl=ASSETS_DIR / "br_hoabinh.pkl",
        feats_json=ASSETS_DIR / "br_hoabinh_feats.json",
    ),
    "songbaha": DamConfig(
        dam_id="songbaha",
        dam_name="Sông Ba Hạ",
        data_csv=ASSETS_DIR / "SongBaHa_merged.csv",
        model_pkl=ASSETS_DIR / "rf_songbaha.pkl",
        feats_json=ASSETS_DIR / "rf_songbaha_feats.json",
    ),
    "trian": DamConfig(
        dam_id="trian",
        dam_name="Trị An",
        data_csv=ASSETS_DIR / "TriAn_merged.csv",
        model_pkl=ASSETS_DIR / "dtree_trian.pkl",
        feats_json=ASSETS_DIR / "dtree_trian_feats.json",
    ),
}


# =========================
# 2) LOADERS (CACHED)
# =========================
@st.cache_data(show_spinner=False)
def load_history(cfg: DamConfig) -> pd.DataFrame:
    if not cfg.data_csv.exists():
        raise FileNotFoundError(f"Missing data CSV: {cfg.data_csv}")

    df = pd.read_csv(cfg.data_csv)

    if cfg.time_col not in df.columns:
        raise ValueError(f"CSV must contain time column '{cfg.time_col}'")

    df[cfg.time_col] = pd.to_datetime(df[cfg.time_col], errors="coerce")
    df = df.dropna(subset=[cfg.time_col]).sort_values(cfg.time_col)
    df = df.set_index(cfg.time_col)

    # Ensure numeric columns are numeric when possible
    for c in df.columns:
        if c == cfg.time_col:
            continue
        if df[c].dtype == object:
            df[c] = pd.to_numeric(df[c], errors="ignore")

    return df


@st.cache_resource(show_spinner=False)
def load_model(cfg: DamConfig):
    if not cfg.model_pkl.exists():
        raise FileNotFoundError(f"Missing model file: {cfg.model_pkl}")
    return joblib.load(cfg.model_pkl)


@st.cache_data(show_spinner=False)
def load_feats(cfg: DamConfig) -> List[str]:
    if not cfg.feats_json.exists():
        raise FileNotFoundError(f"Missing feats json: {cfg.feats_json}")
    feats = json.loads(cfg.feats_json.read_text(encoding="utf-8"))
    if not isinstance(feats, list) or not all(isinstance(x, str) for x in feats):
        raise ValueError("feats json must be a JSON list of strings")
    return feats


# =========================
# 3) FEATURE ENGINEERING
# =========================
def _parse_feat_requests(train_feats: List[str]) -> Tuple[Dict[str, List[str]], Dict[str, List[int]]]:
    """
    Parse requested rolling stats and lags from train feature names.

    Expected patterns:
      - {col}__mean_24h, {col}__std_3d, {col}__max_28d, {col}__min_7d
      - {col}__lag_24

    Returns:
      roll_map: col -> list of window tokens like ["24h","3d","7d","14d","28d"] (lowercase)
      lag_map:  col -> list of lags (int)
    """
    roll_map: Dict[str, set] = {}
    lag_map: Dict[str, set] = {}

    for f in train_feats:
        if "__" not in f:
            continue
        col, rest = f.split("__", 1)

        if rest.startswith("lag_"):
            try:
                lag = int(rest.replace("lag_", ""))
                lag_map.setdefault(col, set()).add(lag)
            except Exception:
                continue
            continue

        # rolling stats
        for stat in ("mean_", "std_", "max_", "min_"):
            if rest.startswith(stat):
                win = rest.replace(stat, "").strip().lower()
                # normalize e.g. 24h, 3d, 7d, 14d, 28d
                roll_map.setdefault(col, set()).add(win)
                break

    roll_map_out = {k: sorted(list(v), key=lambda x: (int(x[:-1]), x[-1])) for k, v in roll_map.items()}
    lag_map_out = {k: sorted(list(v)) for k, v in lag_map.items()}
    return roll_map_out, lag_map_out


def _to_pandas_window(token: str) -> str:
    """
    Convert '24h' -> '24H', '3d' -> '3D', etc.
    """
    token = token.strip().lower()
    if token.endswith("h"):
        return f"{int(token[:-1])}H"
    if token.endswith("d"):
        return f"{int(token[:-1])}D"
    raise ValueError(f"Unsupported window token: {token}")


def build_row_features_at_T(
    df_history: pd.DataFrame,
    train_feats: List[str],
    T: pd.Timestamp,
    lookback_days_buffer: int = 60,
) -> Tuple[pd.DataFrame, Dict[str, float]]:
    """
    Build a single-row feature dataframe for the selected target time T.

    IMPORTANT (anchor logic):
      - All rolling/lag features are computed at the last available observation time A < T (anchor),
        so that gaps right before T do not break feature construction.
      - Calendar/time features (hour/dow/month/is_weekend) are computed from T (the time you want to predict).

    Returns:
      X_row: shape (1, n_features) aligned to train_feats order
      meta:  diagnostics (anchor_time, gap_hours, etc.)
    """
    meta: Dict[str, float] = {}

    if df_history.empty:
        return pd.DataFrame(columns=train_feats), meta

    # Ensure naive timestamps (demo simplification)
    if df_history.index.tz is not None:
        df_history = df_history.copy()
        df_history.index = df_history.index.tz_convert(None)

    T = pd.Timestamp(T).to_pydatetime()
    T = pd.Timestamp(T)

    # 1) Anchor A = last timestamp strictly before T
    hist_before = df_history[df_history.index < T]
    if hist_before.empty:
        meta["gap_hours"] = float("nan")
        return pd.DataFrame(columns=train_feats), meta

    A = hist_before.index.max()
    meta["anchor_time"] = A.isoformat()
    meta["gap_hours"] = float((T - A).total_seconds() / 3600.0)

    # 2) Work on a buffered history ending at A
    start_time = A - pd.Timedelta(days=lookback_days_buffer)
    df_buf = df_history[(df_history.index >= start_time) & (df_history.index <= A)].copy()
    df_buf = df_buf.sort_index()

    meta["n_rows_in_buffer"] = float(len(df_buf))

    # 3) Which rolling windows and lags are required by the model?
    roll_map, lag_map = _parse_feat_requests(train_feats)

    # 4) Build feature frame on the same index as df_buf
    feat = pd.DataFrame(index=df_buf.index)

    # 4.1 Calendar features from T (target time)
    feat["hour"] = int(T.hour)
    feat["dow"] = int(T.dayofweek)
    feat["month"] = int(T.month)
    feat["is_weekend"] = int(T.dayofweek >= 5)

    # 4.2 Rolling stats at time A (anchor)
    for col, windows in roll_map.items():
        if col not in df_buf.columns:
            continue
        s = pd.to_numeric(df_buf[col], errors="coerce")
        s_shift = s.shift(1)  # exclude current anchor row itself, consistent with training notebooks

        for wtoken in windows:
            w = _to_pandas_window(wtoken)
            r = s_shift.rolling(w, closed="left")

            mean_name = f"{col}__mean_{wtoken}"
            std_name = f"{col}__std_{wtoken}"
            max_name = f"{col}__max_{wtoken}"
            min_name = f"{col}__min_{wtoken}"

            if mean_name in train_feats:
                feat[mean_name] = r.mean()
            if std_name in train_feats:
                feat[std_name] = r.std()
            if max_name in train_feats:
                feat[max_name] = r.max()
            if min_name in train_feats:
                feat[min_name] = r.min()

    # 4.3 Lags at time A (row-based shifts)
    for col, lags in lag_map.items():
        if col not in df_buf.columns:
            continue
        s = pd.to_numeric(df_buf[col], errors="coerce")
        for l in lags:
            name = f"{col}__lag_{l}"
            if name in train_feats:
                feat[name] = s.shift(l)

    # 5) Extract row at anchor A; reindex to train_feats
    if A not in feat.index:
        return pd.DataFrame(columns=train_feats), meta

    X_row = feat.loc[[A]].reindex(columns=train_feats)

    # 6) Diagnostics
    meta["n_missing_feats"] = float(X_row.isna().sum(axis=1).iloc[0])
    return X_row, meta


def safe_predict(
    cfg: DamConfig,
    T: pd.Timestamp,
    lookback_days_buffer: int = 60,
) -> Tuple[Optional[float], pd.DataFrame, Dict[str, float], Optional[str]]:
    """
    Returns: (pred, X_row, meta, error_message)
    """
    df = load_history(cfg)
    model = load_model(cfg)
    feats = load_feats(cfg)

    # Guard: need at least some history covering rolling windows.
    # We do not hardcode 28 days here because different dams have different feature sets.
    X_row, meta = build_row_features_at_T(df, feats, T, lookback_days_buffer=lookback_days_buffer)

    if X_row.empty:
        return None, X_row, meta, "Không có dữ liệu lịch sử trước thời điểm T để tạo feature."

    if X_row.isna().any(axis=1).iloc[0]:
        missing = X_row.columns[X_row.isna().iloc[0]].tolist()
        # Show only first N to avoid huge message
        show_n = 10
        extra = "" if len(missing) <= show_n else f" (và {len(missing) - show_n} feature khác)"
        msg = f"Không thể dự đoán vì thiếu dữ liệu để tạo đủ feature. Thiếu: {missing[:show_n]}{extra}"
        return None, X_row, meta, msg

    try:
        pred = float(np.asarray(model.predict(X_row)).ravel()[0])
        return pred, X_row, meta, None
    except Exception as e:
        return None, X_row, meta, f"Lỗi khi predict: {e}"


# =========================
# 4) STREAMLIT UI
# =========================
st.set_page_config(page_title="Hydro Forecast Demo", layout="wide")

st.title("Demo dự đoán mực nước thượng lưu (3 đập)")

with st.sidebar:
    st.header("Cấu hình dự đoán")

    dam_label_to_id = {cfg.dam_name: dam_id for dam_id, cfg in DAMS.items()}
    dam_name = st.selectbox("Chọn đập", list(dam_label_to_id.keys()))
    dam_id = dam_label_to_id[dam_name]
    cfg = DAMS[dam_id]

    df_hist = load_history(cfg)
    min_t = df_hist.index.min()
    max_t = df_hist.index.max()

    st.caption(f"Dữ liệu hiện có: {min_t} → {max_t}")

    # Date/time picker
    # Lý do trước đây bạn thấy mặc định 01/12/2025: app chọn mặc định T = timestamp mới nhất trong dữ liệu (max_t).
    default_dt = max_t  # mặc định = thời điểm mới nhất có trong dataset

    # Cho phép chọn T vượt quá phạm vi dữ liệu (ví dụ dự đoán tương lai). Khi đó app vẫn dùng lịch sử < T.
    max_future_days = 365
    max_selectable_date = (max_t + pd.Timedelta(days=max_future_days)).date()

    d = st.date_input(
        "Ngày (T)",
        value=default_dt.date(),
        min_value=min_t.date(),
        max_value=max_selectable_date,
        help=(
            "Bạn có thể chọn ngày sau mốc dữ liệu cuối cùng để dự đoán tương lai; "
            "app sẽ dựng feature từ lịch sử < T."
        ),
    )

    # Giờ chọn dạng dropdown (không dùng slider)
    hour = st.selectbox(
        "Giờ (T)",
        options=list(range(0, 24)),
        index=int(default_dt.hour),
        help="Chọn giờ nguyên theo bước 1 giờ (phút = 00).",
    )

    T = pd.Timestamp(d) + pd.Timedelta(hours=int(hour))
    st.caption("Giờ dự đoán cố định theo bước 1 giờ (phút = 00).")

    st.divider()

    lookback_days_buffer = st.number_input(
        "Số ngày lịch sử (buffer) để dựng feature",
        min_value=30,
        max_value=365,
        value=60,
        step=1,
        help=(
            "App sẽ lấy dữ liệu trong khoảng [T - buffer, T) để tính rolling/lag. "
            "Nên đặt >= 28 ngày (và lớn hơn nếu dữ liệu sát T có thể bị thiếu)."
        ),
    )

    history_view_days = st.selectbox(
        "Hiển thị lịch sử trước T",
        options=[7, 28, 60, 120],
        index=1,
        format_func=lambda x: f"{x} ngày",
    )

    show_features = st.checkbox("Hiển thị vector feature đầu vào", value=False)

    # Thông tin nhanh về rolling windows mà model đang dùng
    feats_tmp = load_feats(cfg)
    roll_map_tmp, _ = _parse_feat_requests(feats_tmp)
    windows_all = sorted({w for ws in roll_map_tmp.values() for w in ws}, key=lambda x: (int(x[:-1]), x[-1]))
    if windows_all:
        st.caption(f"Rolling windows trong model: {', '.join(windows_all)}")
    st.caption("Lưu ý: rolling cho thời điểm T được tính bằng cách thêm một dòng giả tại T, chỉ dùng dữ liệu < T (không leakage).")

col1, col2 = st.columns([1, 1], gap="large")

with col1:
    st.subheader("Kết quả")
    if st.button("Predict", type="primary"):
        pred, X_row, meta, err = safe_predict(cfg, T, lookback_days_buffer=int(lookback_days_buffer))

        if err is not None:
            st.error(err)
        else:
            st.success(f"Mực nước thượng lưu dự đoán tại T = {T}: **{pred:.4f} m**")

        # Diagnostics
        st.markdown("**Chẩn đoán dữ liệu**")
        if "last_obs_time" in meta:
            st.write(f"- Bản ghi gần nhất trước T: {meta['last_obs_time']}")
        if "gap_hours" in meta:
            st.write(f"- Gap (giờ) từ T đến bản ghi gần nhất: {meta['gap_hours']:.2f}")
        if "n_past_rows" in meta:
            st.write(f"- Số dòng lịch sử dùng để dựng feature (buffer {int(lookback_days_buffer)} ngày): {int(meta['n_past_rows'])}")
        if "n_missing_feats" in meta:
            st.write(f"- Số feature bị thiếu (NaN): {int(meta['n_missing_feats'])}")

        if show_features and not X_row.empty:
            st.dataframe(X_row.T, use_container_width=True, height=480)

with col2:
    st.subheader("Lịch sử gần T")
    # Hiển thị lịch sử trong N ngày trước T (theo lựa chọn sidebar)
    df_hist = load_history(cfg)
    start_view = T - pd.Timedelta(days=int(history_view_days))
    hist_slice = df_hist.loc[(df_hist.index >= start_view) & (df_hist.index < T)].copy()

    # Giới hạn số dòng hiển thị để UI không quá nặng (nhưng vẫn đủ cho 28 ngày với dữ liệu dày)
    hist_slice = hist_slice.tail(5000)
    if hist_slice.empty:
        st.info("Chưa có lịch sử trước T.")
    else:
        st.caption(f"Hiển thị: {start_view} → {T} (tối đa 5000 dòng)")
        st.dataframe(hist_slice, use_container_width=True, height=600)